# IME
exec-once=pgrep fcitx5 || fcitx5 -d

# XWayland
exec-once=xwayland-satellite :11

# Monitor profile
exec-once=kanshi

# Display scaling
#exec-once=echo 'Xft.dpi: 144' | xrdb -m

# Sunshine streaming
exec-once=sunshine

# Clipboard sync
exec-once=~/.local/bin/sync_x11_clip & disown

# Screen warmth
exec-once=gammastep -l 39.9:116.3 -t 3500:3000 -r -P

# Clipboard history
exec-once=wl-paste --watch cliphist store

# Kanata key remapper
exec-once=kanata

# DMS
#exec-once=dms run
