# ============================================================
# Window Rules (migrated from niri)
# ============================================================

# Open maximized for specific apps
windowrule=isfloating:0,appid:floorp
windowrule=isfloating:0,appid:mpv
windowrule=isfloating:0,appid:swayimg
windowrule=isfloating:0,appid:gamescope
windowrule=isfloating:0,appid:org.pipewire.Helvum
windowrule=isfloating:0,appid:code
windowrule=isfloating:0,appid:ONLYOFFICE
windowrule=isfloating:0,appid:jetbrains-idea
windowrule=isfloating:0,appid:Moonlight
windowrule=isfloating:0,appid:Emacs
windowrule=isfloating:0,appid:OBS
windowrule=isfloating:0,appid:calibre-gui
windowrule=isfloating:0,appid:calibre-ebook-viewer
windowrule=isfloating:0,title:另存为

# Open maximized for media/gaming apps
windowrule=isfloating:0,appid:yesplaymusic
windowrule=isfloating:0,appid:QQ
windowrule=isfloating:0,appid:wechat
windowrule=isfloating:0,appid:SPlayer
windowrule=isfloating:0,appid:chromium
windowrule=isfloating:0,appid:helium

# Flameshot floating
windowrule=isfloating:1,appid:flameshot

# Show the key floating with custom size
windowrule=isfloating:1,appid:showmethekey-gtk
