hl.on("hyprland.start", function()
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("bar-rs open")
  hl.exec_cmd("~/.config/niri/scripts/fcitx5.fish")
  hl.exec_cmd("echo 'Xft.dpi: 144' | xrdb -m")
  hl.exec_cmd("gammastep -l 39.9:116.3 -t 3500:3000 -r -P")
  hl.exec_cmd("kanata")
  hl.exec_cmd("kanshi")
  hl.exec_cmd("~/.local/bin/sync_x11_clip")
  hl.exec_cmd("sunshine")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --watch cliphist store")
end)
