# vim:ft=dosini
# foot/bindings.ini

[key-bindings]
# unbind default to avoid conflict
show-urls-launch=none
prompt-prev=none

scrollback-up-half-page=Control+Shift+k
scrollback-down-half-page=Control+Shift+j

show-urls-launch=Control+Shift+f
show-urls-copy=Control+Shift+y

spawn-terminal=Control+Shift+m


search-start=Control+slash

pipe-scrollback=[sh -c "cat > /tmp/pipe-output.txt"]Control+Shift+n

[search-bindings]
# unbind default to avoid conflict
delete-to-end=none

extend-char=Control+l
extend-backward-char=Control+h
commit=Return

