# vim:ft=dosini
# foot/foot.ini

include=~/.config/foot/bindings.ini

font=Maple Mono NF CN:size=16

locked-title=yes

[scrollback]
lines=16383

[url]
launch=floorp ${url}

[colors-dark]
alpha = 0.80
# alpha = 0.75
blur = true
foreground=ffffff
background=000000

[main]
term=foot
gamma-correct-blending=no
selection-target=both

[security]
osc52=enabled

